### PR TITLE
RTL support

### PR DESCRIPTION
**Pull request by btargac**
hi @asmyshlyaev177 , I tried to figure out how scrolling left and right worked, then updated the necessary methods that I saw necessary. Updated some tests that were broken with the updates.

sorry that I could not add any rtl specific tests since I don't know jest virtual dom or js dom supports direction attribute and respect that on rendering ?

### CODE REVIEW

**Comment by asmyshlyaev177** [comment]
Will review it later.

**Comment by kucukharf** [comment]
Hi @asmyshlyaev177, 
Have you had the opportunity to review @btargacs' PR, We need RTL support and really great to have this feature.

**Comment by asmyshlyaev177** [comment]
> Hi @asmyshlyaev177,
> Have you had the opportunity to review @btargac PR, We need RTL support and really great to have this feature.

Sorry for late answer. Please check that command `npm run build` does not get errors.

**Comment by kucukharf** [comment]
Thanks @asmyshlyaev177

**Pull request merged**
